### ISSUE TITLE
ffmpeg._run.Error: ffprobe error (see stderr output for detail)

### ISSUE THREAD

**Issue by sunkymepro** [YuvalNirkin/fsgan#126]
Thanks for your project，it‘s very useful for me.But when I run swap.py or reenact.py,I meet an error,and I don't know how to solve it.
The error is:

Traceback (most recent call last):
  File "reenact.py", line 444, in <module>
    main(**vars(parser.parse_args()))
  File "reenact.py", line 438, in main
    face_reenactment(source[0], target[0], output, select_source, select_target)
  File "reenact.py", line 220, in __call__
    source_cache_dir, source_seq_file_path, _ = self.cache(source_path)
  File "/opt/data/private/fsgan/fsgan/preprocess/preprocess_video.py", line 499, in cache
    self.process_pose(input_path, output_dir, seq_file_path)
  File "/opt/data/private/fsgan/fsgan/preprocess/preprocess_video.py", line 250, in process_pose
    in_vid = VideoInferenceDataset(curr_vid_path, transform=img_transforms)
  File "/opt/data/private/fsgan/fsgan/datasets/video_inference_dataset.py", line 29, in __init__
    self.width, self.height, self.total_frames, self.fps = get_video_info(vid_path)
  File "/opt/data/private/fsgan/fsgan/utils/video_utils.py", line 224, in get_video_info
    return get_media_info(vid_path)
  File "/opt/data/private/fsgan/fsgan/utils/video_utils.py", line 207, in get_media_info
    probe = ffmpeg.probe(media_path)
  File "/root/anaconda3/envs/lixin_py38/lib/python3.8/site-packages/ffmpeg/_probe.py", line 23, in probe
    raise Error('ffprobe', out, err)
ffmpeg._run.Error: ffprobe error (see stderr output for detail)

I run swap.py by inputing 'python swap.py one.mp4 -t two.mp4 -o . --seg_remove_mouth',I notice that when the program calls the function process_pose,it inputs a paramater 'seq_file_path',I output this paramater and its value is '/opt/data/private/fsgan/fsgan/inference/one/one_seq01.mp4',but there is no this file,there only exist 'xx_dsfd.pkl','xx_dsfd_seq.pkl','xx_seq00_dsfd_seq.pkl' and 'xx_seq01_dsfd_seq.pkl' ('xx' denotes the name of my input mp4 file)
Can you tell me what's wrong?I really need the result

Thanks

**Comment by YuvalNirkin** [comment]
It might be that no faces were detected for one of the videos. Try with different videos (maybe easier ones) and see if the error still occurs.

**Comment by sunkymepro** [comment]
> It might be that no faces were detected for one of the videos. Try with different videos (maybe easier ones) and see if the error still occurs.

I try the example videos（conan_obrien.mp4 and shinzo_abe.mp4），it also appears the same error

**Comment by YuvalNirkin** [comment]
Maybe you don't have ffmpeg installed on your system. Follow the installation guide on how to install it.

**Comment by sunkymepro** [comment]
> Maybe you don't have ffmpeg installed on your system. Follow the installation guide on how to install it.

I directly install ffmpeg by pip，I will try to install ffmpeg as installation
Besides，I want to use the model except reenact to swap two pictures with the same pose，now I have two pictures but I don’t know the size of theinput tensor of the seg net，and what preprocess should I do，can you tell me？
Thanks

**Comment by msx-123** [comment]
May I ask, I have reinstalled FFMPEG for many times, but this problem still appears, is there any other solution, thank you。
By the way, I installed it under Anconda。

**Comment by skymanaditya1** [comment]
I am also facing the same issue with the example videos. I installed ffmpeg using pip, and my version is 4.0.2. Any solution to this @YuvalNirkin ?

**Comment by soumyajee** [comment]
AttributeError: module 'ffmpeg' has no attribute 'probe'
how to resolve this issue
