### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1uyEETpnuvfwZeQLvlP8SzahrMBwst9Be (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9481ba6550>: Failed to establish a new connection: [Errno 110] Connection timed out'))

### ISSUE THREAD

**Issue by zhouzikang** [YuvalNirkin/fsgan#164]
1. first I follow the guide
`git clone https://github.com/YuvalNirkin/fsgan
cd fsgan
conda env create -f fsgan_env.yml
conda activate fsgan
pip install .    # Alternatively add the root directory of the repository to PYTHONPATH.`

2. and then I follow the Ubuntu Installation Guide

3. but when I run
`python download_fsgan_models.py`

**There is a problem here：**
`(fsgan) yukang@yukang:/data/dev/projects/fsgan$ python download_fsgan_models.py
[1/15] Downloading "ijbc_msrunet_256_2_0_reenactment_v1.pth"...
ERROR:root:Traceback (most recent call last):
  File "/home/yukang/anaconda3/envs/fsgan/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/yukang/anaconda3/envs/fsgan/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/yukang/anaconda3/envs/fsgan/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yukang/anaconda3/envs/fsgan/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/yukang/anaconda3/envs/fsgan/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/yukang/anaconda3/envs/fsgan/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/yukang/anaconda3/envs/fsgan/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/yukang/anaconda3/envs/fsgan/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f9481ba6550>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yukang/anaconda3/envs/fsgan/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/yukang/anaconda3/envs/fsgan/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/yukang/anaconda3/envs/fsgan/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1uyEETpnuvfwZeQLvlP8SzahrMBwst9Be (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9481ba6550>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/dev/projects/fsgan/download_fsgan_models.py", line 77, in main
    download_from_url(link, out_path)
  File "/data/dev/projects/fsgan/fsgan/utils/utils.py", line 260, in download_from_url
    response = session.get(url, stream=True)
  File "/home/yukang/anaconda3/envs/fsgan/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/yukang/anaconda3/envs/fsgan/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yukang/anaconda3/envs/fsgan/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/yukang/anaconda3/envs/fsgan/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1uyEETpnuvfwZeQLvlP8SzahrMBwst9Be (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9481ba6550>: Failed to establish a new connection: [Errno 110] Connection timed out'))`
![Screenshot from 2022-11-20 15-40-20](https://user-images.githubusercontent.com/77162542/202891310-8148eaf7-13b4-42eb-b957-5d58ab19a69f.png)

4. Then I try to open the url in the browser
5. but 
![Screenshot from 2022-11-20 15-53-48](https://user-images.githubusercontent.com/77162542/202891685-3b30146a-0b78-4f82-914e-05641923edc0.png)
How can I solve this problem? Thank you very much.Sorry to bother  @YuvalNirkin

**Comment by YuvalNirkin** [comment]
The links are working.
Google might be blocked in your country.

**Comment by zhouzikang** [comment]
> The links are working. Google might be blocked in your country.

Sorry to bother @YuvalNirkin, I'm very interested in your research. Could you please send them to my mailbox?zhouzk5@mail2.sysu.edu.cn

Thanks again!

**Comment by zhouzikang** [comment]
I solve the problem by I found these files already in the mailbox.
