### ISSUE TITLE
RuntimeError: unexpected EOF, expected 1880922 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by hsl20130659** [YuvalNirkin/fsgan#18]
Traceback (most recent call last):
  File "/home/hsl/Project/Face-swap/fsgan/swap.py", line 501, in <module>
    main(parser.parse_args())
  File "/home/hsl/Project/Face-swap/fsgan/swap.py", line 490, in main
    blending_model=blending_model, criterion_id=criterion_id, min_radius=min_radius, output_crop=output_crop)
  File "/home/hsl/Project/Face-swap/fsgan/swap.py", line 131, in __init__
    self.Gr, checkpoint = load_model(reenactment_model, 'face reenactment', self.device, return_checkpoint=True)
  File "/home/hsl/Project/Face-swap/fsgan/fsgan/utils/utils.py", line 166, in load_model
    checkpoint = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "/home/hsl/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "/home/hsl/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 549, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 1880922 more bytes. The file might be corrupted.

I meet this problem and have no idea to address  it

**Comment by YuvalNirkin** [comment]
The model probably wasn't downloaded correctly. Try to download it again.
