### ISSUE TITLE
AssertionError: Failed to read frame 592 from input video:

### ISSUE THREAD

**Issue by thelordlugo** [YuvalNirkin/fsgan#21]
hi i get this when trying to faceswap, reenact works fine

Process FaceSwappingRenderer-1:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/data/dev/projects/fsgan/utils/video_renderer.py", line 159, in run
    assert frame_bgr is not None, f'Failed to read frame {i} from input video: "{self._in_vid_path}"'
AssertionError: Failed to read frame 592 from input video: "/data/dev/projects/videos/conan_obrien.mp4"

**Comment by thelordlugo** [comment]
never-mind fixed it
