### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by GarethWright** [YuvalNirkin/fsgan#30]
(fgan) D:\data\dev\projects>python download_fsgan_models.py
Traceback (most recent call last):
  File "download_fsgan_models.py", line 8, in <module>
    from fsgan.utils.utils import download_from_url
  File "D:\data\dev\projects\fsgan\utils\utils.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by GarethWright** [comment]
The below missing from windows instructions

```
python -m pip install requests 
python -m pip install tqdm
```
