### ISSUE TITLE
If there are any variants to run script on 8GB VRAM?

### ISSUE THREAD

**Issue by ilowen** [YuvalNirkin/fsgan#49]

**Comment by YuvalNirkin** [comment]
Just call the script with lower values for all batch* arguments, most importantly the "det_batch_size" argument.

**Comment by KJYoo1989** [comment]
@ilowen hey were you successful getting it to run on 8GB VRAM? I have a 1080 TI with 11GB and I am getting this even when I am trying to run the conan/abe example.

`RuntimeError: CUDA out of memory. Tried to allocate 1014.00 MiB (GPU 0; 11.00 GiB total capacity; 6.95 GiB already allocated; 621.45 MiB free; 8.07 GiB reserved in total by PyTorch)`

Any thoughts?

**Comment by ilowen** [comment]
@KJYoo1989 Yes. I had edit all batches and it's work fine!

**Comment by KJYoo1989** [comment]
@ilowen: When @YuvalNirkin says "call the script with lower values for all batch* arguments" what does that actually mean. I have called the batch size to be even 1, but I still get the same error. I am very much new to python/cuda. Thank you so much in advance!

`python swap.py ../docs/examples/shinzo_abe.mp4 -t ../docs/examples/conan_obrien.mp4 -o . --seg_remove_mouth -b 1`

KJ

**Comment by ilowen** [comment]
just edit *.py files in peject not all variabelse have transmited to console args

**Comment by YuvalNirkin** [comment]
All variables are also console arguments. You can see them with:
```
python swap.py --help
```

I assumed a minimum of 11GB of VRAM also taking speed into account. The defaults can't account for all cases, specifically for the detection stage which operates on variable resolutions.

**Comment by Greg-Tarr** [comment]
@KJYoo1989 and others who are facing this issue, the command you mentioned with the `-b 1` will not provide a sufficient decrease in VRAM to run on 8 or 6GB VRAM. **However by adding `-db 1` you can achieve this:**

`python swap.py ../docs/examples/shinzo_abe.mp4 -t ../docs/examples/conan_obrien.mp4 -o . --finetune --finetune_save --seg_remove_mouth -b 1 -db 1`

I was able to get this running on a GTX 1060 6GB graphics card - albeit at 2.09 frames per second.

**Comment by Greg-Tarr** [comment]
An alternative is this fork I have made, which does not hold every model in VRAM at once, during inference of each model it loads them into VRAM, does inference, then unloads them. Saving VRAM at the cost of speed.

Here is the branch: https://github.com/Greg-Tarr/fsgan/tree/low-vram

Git clone that instead of fsgan, and run with:

python swap.py ../docs/examples/shinzo_abe.mp4 -t ../docs/examples/conan_obrien.mp4 -o . -b 1 -db 1 -pb 1 -lb 1 -sb 1 --finetune --finetune_save --seg_remove_mouth

GPU VRAM usage maxes out at 5.7GB - VERY close to my maximum of 6GB. If this doesn't work, remove the finetuning.

**Comment by mayanktiwariiiitdmj** [comment]
> python swap.py ../docs/examples/shinzo_abe.mp4 -t ../docs/examples/conan_obrien.mp4 -o . -b 1 -db 1 -pb 1 -lb 1 -sb 1 --finetune --finetune_save --seg_remove_mouth

When I am executing the above command, I am getting the following error. [I am using NVIDIA GTX 1660i 6GB]

```
(init_fcgan) C:\data\dev\projects\fsgan\inference>python swap.py ../docs/examples/shinzo_abe.mp4 -t ../docs/examples/conan_obrien.mp4 -o . -b 1 -db 1 -pb 1 -lb 1 -sb 1 --finetune --finetune_save --seg_remove_mouth
=> using GPU devices: 0
=> Loading face pose model: "hopenet_robust_alpha1.pth"...
=> Loading face landmarks model: "hr18_wflw_landmarks.pth"...
=> Loading face segmentation model: "celeba_unet_256_1_2_segmentation_v2.pth"...
=> Loading face reenactment model: "nfv_msrunet_256_1_2_reenactment_v2.1.pth"...
=> Loading face completion model: "ijbc_msrunet_256_1_2_inpainting_v2.pth"...
=> Loading face blending model: "ijbc_msrunet_256_1_2_blending_v2.pth"...

        OpenH264 Video Codec provided by Cisco Systems, Inc.

=> Finetuning the reenactment generator on: "shinzo_abe_seq00.mp4"...
  0%|                                                                            | 0/200 [00:05<?, ?batches/s]
Traceback (most recent call last):
  File "swap.py", line 504, in <module>
    main(**vars(parser.parse_args()))
  File "swap.py", line 498, in main
    face_swapping(source[0], target[0], output, select_source, select_target)
  File "swap.py", line 280, in __call__
    self.finetune(src_vid_seq_path, self.finetune_save)
  File "swap.py", line 208, in finetune
    img_pred = self.Gr(input)
  File "C:\ProgramData\Anaconda3\envs\init_fcgan\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\data\dev\projects\fsgan\models\res_unet.py", line 343, in forward
    x = self.base.inner(x)
  File "C:\ProgramData\Anaconda3\envs\init_fcgan\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\data\dev\projects\fsgan\models\res_unet.py", line 192, in forward
    return self.flat_block(x)
  File "C:\ProgramData\Anaconda3\envs\init_fcgan\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\data\dev\projects\fsgan\models\res_unet.py", line 154, in forward
    return self.model(x)
  File "C:\ProgramData\Anaconda3\envs\init_fcgan\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\init_fcgan\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\ProgramData\Anaconda3\envs\init_fcgan\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\data\dev\projects\fsgan\models\res_unet.py", line 123, in forward
    out = x + self.model(x)
  File "C:\ProgramData\Anaconda3\envs\init_fcgan\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\init_fcgan\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\ProgramData\Anaconda3\envs\init_fcgan\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\init_fcgan\lib\site-packages\torch\nn\modules\conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "C:\ProgramData\Anaconda3\envs\init_fcgan\lib\site-packages\torch\nn\modules\conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 6.00 GiB total capacity; 4.03 GiB already allocated; 23.85 MiB free; 4.22 GiB reserved in total by PyTorch)
```
Please help me.

**Comment by quirijnve** [comment]
I have the same problem at the finetuning reenactment procces, even adding fb 1 doesnt work

**Comment by YuvalNirkin** [comment]
I reduced the default batch sizes to support lower memory consumption.
If this is still not enough, disable the finetuning stage.
