### ISSUE TITLE
Could not find encoder for codec id 27: Encoder not found

### ISSUE THREAD

**Issue by lulin60** [YuvalNirkin/fsgan#70]

**Comment by YuvalNirkin** [comment]
Please provide more details.

**Comment by Greg-Tarr** [comment]
@YuvalNirkin Came across same error on ubuntu 16.04:

**Comment by Greg-Tarr** [comment]
I can confirm this solves the issue. Thank you and very good work!

**Comment by DrCrayRay** [comment]
> You're missing the avc1 encoder. You can try using a different encoder by adding the following argument:
> 
> ```
> --encoder_codec mp4v
> ```
> 
> Though this will reduce the quality of the video.

Sorry  where do I type that?

**Comment by Greg-Tarr** [comment]
@DrCrayRay add it onto the end of the command.

**Comment by Better369** [comment]
> 

Hello, how to add, sorry, I didn't understand，Why do I show up after adding "unrecognized arguments: mp4v"

**Comment by manojjthomas** [comment]
> You're missing the avc1 encoder. You can try using a different encoder by adding the following argument:
> 
> ```
> --encoder_codec mp4v
> ```
> 
> Though this will reduce the quality of the video.

Getting the same encoder error, even with alternate option:
python fsgan/inference/swap.py docs/examples/shinzo_abe.mp4 -t docs/examples/conan_obrien.mp4 -o . --seg_remove_mouth --encoder_codec mp4v


=> Cropping video sequences from video: "shinzo_abe.mp4"...
=> Computing face poses for video: "shinzo_abe_seq00.mp4"...
Traceback (most recent call last):
  File "/data/dev/projects/fsgan/fsgan/inference/swap.py", line 504, in <module>
    main(**vars(parser.parse_args()))
  File "/data/dev/projects/fsgan/fsgan/inference/swap.py", line 498, in main
    face_swapping(source[0], target[0], output, select_source, select_target)
  File "/data/dev/projects/fsgan/fsgan/inference/swap.py", line 239, in __call__
    source_cache_dir, source_seq_file_path, _ = self.cache(source_path)
  File "/data/dev/projects/fsgan/fsgan/preprocess/preprocess_video.py", line 469, in cache
    self.process_pose(input_path, output_dir, seq_file_path)
  File "/data/dev/projects/fsgan/fsgan/preprocess/preprocess_video.py", line 247, in process_pose
    in_vid = VideoInferenceDataset(curr_vid_path, transform=img_transforms)
  File "/data/dev/projects/fsgan/fsgan/datasets/video_inference_dataset.py", line 29, in __init__
    self.width, self.height, self.total_frames, self.fps = get_video_info(vid_path)
  File "/data/dev/projects/fsgan/fsgan/utils/video_utils.py", line 223, in get_video_info
    return get_media_info(vid_path)
  File "/data/dev/projects/fsgan/fsgan/utils/video_utils.py", line 206, in get_media_info
    probe = ffmpeg.probe(media_path)
  File "/home/ubuntu/anaconda3/envs/fsgan/lib/python3.9/site-packages/ffmpeg/_probe.py", line 23, in probe
    raise Error('ffprobe', out, err)
ffmpeg._run.Error: ffprobe error (see stderr output for detail)

Any suggestions would help, before I try windows :)

**Comment by swerizwan** [comment]
The path is correct and the video is also not corrupted why I am getting that error? I have checked it on other videos as well, as error again and again. 

Processing dataset
  0%|                                                                                               | 0/1 [00:00<?, ?it/s]The video file '/assets/data/EMOCA_test_example_data/videos/82-25-854x480_affwild2.mp4' is corrupted. Skipping it.
100%|███████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54.12it/s]
Traceback (most recent call last):
  File "gdl_apps/EMOCA/demos/test_emoca_on_video.py", line 172, in <module>
    main()
  File "gdl_apps/EMOCA/demos/test_emoca_on_video.py", line 167, in main
    reconstruct_video(args)
  File "gdl_apps/EMOCA/demos/test_emoca_on_video.py", line 62, in reconstruct_video
    dm.prepare_data()
  File "/home/abbas/anaconda3/envs/emoo36/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 428, in wrapped_fn
    fn(*args, **kwargs)
  File "/home/abbas/emoca/gdl/datasets/FaceVideoDataModule.py", line 3191, in prepare_data
    self._gather_data(exist_ok=True)
  File "/home/abbas/emoca/gdl/datasets/FaceVideoDataModule.py", line 3213, in _gather_data
    self._gather_video_metadata()
  File "/home/abbas/emoca/gdl/datasets/FaceVideoDataModule.py", line 1569, in _gather_video_metadata
    del self.annotation_list[vi]
IndexError: list assignment index out of range
