### ISSUE TITLE
preprocess_video.py to preprocess IJB-C　error

### ISSUE THREAD

**Issue by satoshikanno** [YuvalNirkin/fsgan#90]
I ran preprocess_video.py to preprocess IJB-C. The following error occurs.
”RuntimeError: Cache file does not exist: C:\data\datasets\IJB-C\images\video\1\1_dsfd_seq.pkl”
What should I do?

**Comment by YuvalNirkin** [comment]
Does it work on other videos?

**Comment by imgsrc-dev** [comment]
The process doesn't complete on the other videos, I get the same error.
I get the same error.
RuntimeError: Cache file does not exist
How should I respond?

```
ERROR:root:Traceback (most recent call last):
  File "C:\data\dev\projects\fsgan\utils\batch.py", line 78, in main
    func_obj(*curr_input) if ignore_output else func_obj(*curr_input, out_vid_path)
  File "preprocess_video.py", line 490, in __call__
    return self.cache(input_path, output_dir)
  File "preprocess_video.py", line 459, in cache
    encoder_codec=self.encoder_codec)
  File "C:\data\dev\projects\fsgan\preprocess\crop_video_sequences.py", line 23, in main
    raise RuntimeError('Cache file does not exist: ' + cache_path)
RuntimeError: Cache file does not exist: C:
```

**Comment by satoshikanno** [comment]
The process doesn't complete on the other videos, I get the same error.
It's a video, not an image.
I get the same error.
RuntimeError: Cache file does not exist
How should I respond?

ERROR:root:Traceback (most recent call last):
  File "C:\data\dev\projects\fsgan\utils\batch.py", line 78, in main
    func_obj(*curr_input) if ignore_output else func_obj(*curr_input, out_vid_path)
  File "preprocess_video.py", line 490, in __call__
    return self.cache(input_path, output_dir)
  File "preprocess_video.py", line 459, in cache
    encoder_codec=self.encoder_codec)
  File "C:\data\dev\projects\fsgan\preprocess\crop_video_sequences.py", line 23, in main
    raise RuntimeError('Cache file does not exist: ' + cache_path)
RuntimeError: Cache file does not exist: C:

**Comment by Kakoedlinnoeslovo** [comment]
Hi, @satoshikanno, open this video, I think there is no face in it.
